# Generated by Django 4.0.3 on 2022-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_remove_produto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
