# Generated by Django 4.0.3 on 2022-04-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_carro_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto_carro', to='loja.produto'),
        ),
    ]
